# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1234, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1234, 750))
        icon = QtGui.QIcon.fromTheme("icon.png")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(2, 3, 1231, 742))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.raion = QtWidgets.QLineEdit(self.layoutWidget)
        self.raion.setMinimumSize(QtCore.QSize(0, 25))
        self.raion.setText("")
        self.raion.setObjectName("raion")
        self.horizontalLayout_2.addWidget(self.raion)
        self.find = QtWidgets.QPushButton(self.layoutWidget)
        self.find.setObjectName("find")
        self.find.setMinimumSize(QtCore.QSize(70, 25))
        self.horizontalLayout_2.addWidget(self.find)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter = QtWidgets.QComboBox(self.layoutWidget)
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.horizontalLayout.addWidget(self.filter)
        self.errors = QtWidgets.QLabel(self.layoutWidget)
        self.errors.setText("")
        self.errors.setObjectName("errors")
        self.horizontalLayout.addWidget(self.errors)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.list = QtWidgets.QListWidget(self.layoutWidget)
        self.list.setMaximumSize(QtCore.QSize(522, 690))
        self.list.setObjectName("list")
        self.horizontalLayout_3.addWidget(self.list)
        self.brs = QtWebEngineWidgets.QWebEngineView(self.layoutWidget)
        self.brs.setMinimumSize(QtCore.QSize(800, 0))
        self.brs.setProperty("url", QtCore.QUrl("about:blank"))
        self.brs.setObjectName("brs")
        self.horizontalLayout_3.addWidget(self.brs)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Newsify"))
        self.find.setText(_translate("MainWindow", "Поиск"))
        self.filter.setItemText(0, _translate("MainWindow", "Все"))
        self.filter.setItemText(1, _translate("MainWindow", "Культура"))
        self.filter.setItemText(2, _translate("MainWindow", "Наука"))
        self.filter.setItemText(3, _translate("MainWindow", "Технологии"))
        self.filter.setItemText(4, _translate("MainWindow", "Политика"))
        self.filter.setItemText(5, _translate("MainWindow", "Правительство"))
        self.filter.setItemText(6, _translate("MainWindow", "Проишествие"))
        self.filter.setItemText(7, _translate("MainWindow", "Религия"))
        self.filter.setItemText(8, _translate("MainWindow", "Спорт"))
        self.filter.setItemText(9, _translate("MainWindow", "Экономика"))
        self.filter.setItemText(10, _translate("MainWindow", "Музыка"))
        self.filter.setItemText(11, _translate("MainWindow", "Игры"))
        self.filter.setItemText(12, _translate("MainWindow", "Веселье"))
        self.filter.setItemText(13, _translate("MainWindow", "История"))
        self.filter.setItemText(14, _translate("MainWindow", "Природа"))
from PyQt5 import QtWebEngineWidgets
